= ejb-in-ear: Deployment of an EAR Containing a JSF WAR and EJB JAR
:author: Paul Robinson
:productName: WildFly
:productNameFull: WildFly Application Server
:jbossHomeName: WILDFLY_HOME
:productVersion: 12
:buildRequirements: Java 8.0 (Java SDK 1.8) or later and Maven 3.3.1 or later
include::../shared-doc/attributes.adoc[]

:level: Intermediate
:technologies: EJB, EAR
:source: {githubRepoUrl}

[abstract]
The `ejb-in-ear` quickstart demonstrates how to deploy an EAR archive that contains a *JSF* WAR and an EJB JAR.

:standalone-server-type: default
:archiveType: ear

== What is it?

The `ejb-in-ear` quickstart demonstrates the deployment of an EAR artifact to {productNameFull}. The EAR contains a JSF WAR and an EJB JAR.

This example consists of the following Maven projects, each with a shared parent.

[cols="30%,70%",options="headers"]
|===
|Project |Description

| `ejb`
| This project contains the EJB code and can be built independently to produce the JAR archive.

| `web`
| This project contains the JSF pages and the managed bean.

| `ear`
| This project builds the EAR artifact and pulls in the EJB and web artifacts.
|===

The root `pom.xml` builds each of the subprojects in the above order and deploys the EAR archive to the server.

The example follows the common "Hello World" pattern, using the following workflow.

. A JSF page asks for a user name.
. On clicking *Greet*, the name is sent to a managed bean named `Greeter`.
. On setting the name, the `Greeter` invokes the `GreeterEJB`, which was injected to the managed bean. Notice the field is annotated with `@EJB`.
. The response from invoking the `GreeterEJB` is stored in a field (message) of the managed bean.
. The managed bean is annotated as `@SessionScoped`, so the same managed bean instance is used for the entire session. This ensures that the message is available when the page reloads and is displayed to the user.
